# Generated by Django 5.0.1 on 2024-01-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_newmodel_alter_book_description_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
